apiVersion: icp4a.ibm.com/v1
kind: ICP4ACluster
metadata:
  name: baw
  namespace: baw
  labels:
    app.kubernetes.io/instance: ibm-dba
    app.kubernetes.io/managed-by: ibm-dba
    app.kubernetes.io/name: ibm-dba
    release: 24.0.1
spec:
  appVersion: 24.0.1
  ibm_license: accept
  shared_configuration:
    sc_common_service:
      operator_namespace: baw
      services_namespace: baw

    sc_deployment_type: Production
    sc_deployment_platform: ROKS
    sc_deployment_context: CP4A
    sc_deployment_fncm_license: production
    sc_deployment_baw_license: production
    sc_deployment_license: production
    sc_deployment_profile_size: small
    sc_image_repository: cp.icr.io
    sc_ingress_enable: false

    sc_deployment_patterns: "content,workflow"
    sc_optional_components: "cmis,css,kafka"

    image_pull_secrets:
    - ibm-entitlement-key


    sc_iam:
      default_admin_username: cpadmin

    encryption_key_secret: ibm-iaws-shared-key-secret
    root_ca_secret: icp4a-root-ca

    trusted_certificate_list: [cert-tls-ibm-github,cert-tls-letsencrypt-root,cert-tls-letsencrypt-r12,cert-tls-letsencrypt-r13]

    enable_fips: false

    storage_configuration:
      sc_slow_file_storage_classname: ocs-storagecluster-cephfs
      sc_medium_file_storage_classname: ocs-storagecluster-cephfs
      sc_fast_file_storage_classname: ocs-storagecluster-cephfs
      sc_block_storage_classname: ocs-storagecluster-ceph-rbd
      
    sc_audit_logging:
      enabled: false

    sc_egress_configuration:
      sc_restricted_internet_access: false
    
    sc_content_initialization: true
    sc_content_verification: false
    sc_cpe_limited_storage: false
    
   
  ldap_configuration:
    lc_selected_ldap_type: "Custom"
    lc_ldap_server: "verify.ldap.svc.cluster.local"
    lc_ldap_port: "9389"
    lc_ldap_base_dn: "DC=cloudpak"
    lc_ldap_ssl_enabled: false
    lc_bind_secret: ldap-bind-secret
    lc_ldap_user_name_attribute: "*:uid"
    lc_ldap_user_display_name_attr: "cn"
    lc_ldap_group_base_dn: "OU=groups,DC=cloudpak"
    lc_ldap_group_name_attribute: "*:cn"
    lc_ldap_group_display_name_attr: "cn"
    lc_ldap_group_membership_search_filter: "(&(objectclass=groupOfNames)(member={0}))"
    lc_ldap_group_member_id_map: "groupOfNames:member"
    custom:
      lc_user_filter: "(&(objectClass=inetOrgPerson)(uid=%v))"
      lc_group_filter: "(&(objectClass=groupOfNames)(cn=%v))"

  
  datasource_configuration:
    dc_ssl_enabled: false
    dc_icn_datasource:
      database_name: navdbprd
      database_servername: pg-navdb-db-rw.cp4a
      dc_database_type: postgresql
      dc_common_icn_datasource_name: ECMClientDS
      database_port: "5432"
    dc_gcd_datasource:
      database_name: navdbprd
      database_servername: pg-navdb-db-rw.cp4a
      dc_database_type: postgresql
      dc_common_gcd_datasource_name: FNGCDDS
      dc_common_gcd_xa_datasource_name: FNGCDDSXA
      database_port: "5432"
    dc_os_datasources:
    - database_name: bawdocsprd
      database_servername: pg-baw-db-rw.cp4a
      database_port: "5432"
      dc_os_label: bawdocs
      dc_database_type: postgresql
      dc_common_os_datasource_name: BAWDOCS
      dc_common_os_xa_datasource_name: BAWDOCSXA
    - database_name: bawdosprd
      database_servername: pg-baw-db-rw.cp4a
      database_port: "5432"
      dc_os_label: bawdos
      dc_database_type: postgresql
      dc_common_os_datasource_name: BAWDOS
      dc_common_os_xa_datasource_name: BAWDOSXA
    - database_name: bawtosprd
      database_servername: pg-baw-db-rw.cp4a
      database_port: "5432"
      dc_os_label: bawtos
      dc_database_type: postgresql
      dc_common_os_datasource_name: BAWTOS
      dc_common_os_xa_datasource_name: BAWTOSXA


  navigator_configuration:
    ban_secret_name: ibm-ban-secret

    icn_production_setting:
      icn_jndids_name: ECMClientDS
      icn_schema: navdb

  baw_configuration:
  - name: deploy
    liberty_custom_xml: |
      <server>
        <library id="postgresqlJDBCLibRobo">
          <file name="/shared/resources/jdbc/postgresql/postgresql-42.7.2.jar"/>
        </library>

        <dataSource id="jdbc/robo" jndiName="jdbc/robo">
          <jdbcDriver libraryRef="postgresqlJDBCLibRobo"/>
          <properties.postgresql URL="jdbc:postgresql://pg-adp-db-rw.cp4a.svc.cluster.local:5432/postgres?sslmode=disable"
            user="postgres"
            password="password"/>
        </dataSource>

        <dataSource id="jdbc/demo" jndiName="jdbc/demo">
          <jdbcDriver libraryRef="postgresqlJDBCLibRobo"/>
          <properties.postgresql URL="jdbc:postgresql://pg-adp-db-rw.cp4a.svc.cluster.local:5432/postgres?sslmode=disable"
            user="postgres"
            password="password"/>
        </dataSource>

        <variable name="Security.ContentSecurityPolicyHeaderValue" value="default-src 'self';
        frame-ancestors 'self';
        font-src 'self' fonts.gstatic.com 1.www.s81c.com fonts.gstatic.com *.walkme.com data:;
        frame-src * data: https: blob:;
        img-src 'self' *.cloudfront.net *.walkme.com *.cloudfront.net s3.walkmeusercontent.com d2qhvajt3imc89.cloudfront.net data: blob:;
        script-src 'self' 'unsafe-inline' 'unsafe-eval' https:;
        style-src 'self' 'unsafe-inline' *.walkme.com;
        connect-src 'self' *.walkme.com wss: https:;
        worker-src blob:; object-src *.walkme.com" />


        <logging consoleFormat="SIMPLE"
              consoleLogLevel="INFO"
              consoleSource="message,trace,accessLog,ffdc,audit"
              traceFormat="ENHANCED"
              traceSpecification="*=info"
              messageFormat="SIMPLE"
              maxFiles="10"
              maxFileSize="20"/>
      </server>
    capabilities: "workflow"
    admin_user: icpadmin
    workflow_center:
      url: https://hostname/bas/ProcessCenter
      secret_name: ibm-baw-wc-secret
      heartbeat_interval: 30
    database:
      database_name: baw
      type: postgresql
      server_name: pg-navdb-db-rw.cp4a
      port: "5432"
      enable_ssl: false
      secret_name: workflow-authoring-db-secret
      use_custom_jdbc_drivers: false
    environment_config:
      timezone: "Etc/UTC"
      show_task_prioritization_service_toggle: false
      always_run_task_prioritization_service: false
    content_integration:
      domain_name: P8DOMAIN
      object_store_name: BAWDOCS
    case:
      domain_name: P8DOMAIN
      object_store_name_dos: BAWDOS
      tos_list:
      - object_store_name: BAWTOS
        connection_point_name: "pe_conn_bawtos"
        target_environment_name: "target_env"
        is_default: true
    resources:
      limits:
        cpu: 2
        memory: 8Gi
      requests:
        cpu: 1
        memory: 2Gi      

  ecm_configuration:
    graphql:
      graphql_production_setting:
        enable_graph_iql: true
    css:
      css_production_setting:
        icc:
          icc_enabled: true
          icc_secret_name: ibm-icc-secret
          p8domain_name: P8DOMAIN

  initialize_configuration:
    ic_domain_creation:
      domain_name: P8DOMAIN
      encryption_key: "128"
    ic_ldap_creation:
      ic_ldap_admin_user_name:
      - icpadmin
      ic_ldap_admins_groups_name:
      - admins
    ic_obj_store_creation:
      object_stores:
      - oc_cpe_obj_store_display_name: BAWDOCS
        oc_cpe_obj_store_symb_name: BAWDOCS
        oc_cpe_obj_store_conn:
          name: BAWDOCSCONN
          dc_os_datasource_name: BAWDOCS
          dc_os_xa_datasource_name: BAWDOCSXA
        oc_cpe_obj_store_workflow_data_tbl_space: pg_default
        oc_cpe_obj_store_workflow_index_tbl_space: pg_default
        oc_cpe_obj_store_workflow_blob_tbl_space: pg_default
        oc_cpe_obj_store_admin_user_groups:
        - admins
      - oc_cpe_obj_store_display_name: BAWDOS
        oc_cpe_obj_store_symb_name: BAWDOS
        oc_cpe_obj_store_conn:
          name: BAWDOSCONN
          dc_os_datasource_name: BAWDOS
          dc_os_xa_datasource_name: BAWDOSXA
        oc_cpe_obj_store_workflow_data_tbl_space: pg_default
        oc_cpe_obj_store_workflow_index_tbl_space: pg_default
        oc_cpe_obj_store_workflow_blob_tbl_space: pg_default
        oc_cpe_obj_store_admin_user_groups:
        - admins
      - oc_cpe_obj_store_display_name: BAWTOS
        oc_cpe_obj_store_symb_name: BAWTOS
        oc_cpe_obj_store_conn:
          name: BAWTOSCONN
          dc_os_datasource_name: BAWTOS
          dc_os_xa_datasource_name: BAWTOSXA
        oc_cpe_obj_store_enable_workflow: true
        oc_cpe_obj_store_workflow_admin_group: admins
        oc_cpe_obj_store_workflow_config_group: admins
        oc_cpe_obj_store_workflow_data_tbl_space: pg_default
        oc_cpe_obj_store_workflow_index_tbl_space: pg_default
        oc_cpe_obj_store_workflow_blob_tbl_space: pg_default
        oc_cpe_obj_store_workflow_pe_conn_point_name: pe_conn_bawtos
        oc_cpe_obj_store_admin_user_groups:
        - admins
